/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'

const TableSetupLazyRouteImport = createFileRoute('/table/setup')()
const AdminTablesLazyRouteImport = createFileRoute('/admin/tables')()
const AdminStatisticsLazyRouteImport = createFileRoute('/admin/statistics')()
const AdminMenusLazyRouteImport = createFileRoute('/admin/menus')()
const AdminLoginLazyRouteImport = createFileRoute('/admin/login')()
const AdminDashboardLazyRouteImport = createFileRoute('/admin/dashboard')()
const AdminCategoriesLazyRouteImport = createFileRoute('/admin/categories')()
const TableTableNoOrderLazyRouteImport = createFileRoute(
  '/table/$tableNo/order',
)()
const TableTableNoMenuLazyRouteImport = createFileRoute(
  '/table/$tableNo/menu',
)()
const TableTableNoHistoryLazyRouteImport = createFileRoute(
  '/table/$tableNo/history',
)()
const TableTableNoCartLazyRouteImport = createFileRoute(
  '/table/$tableNo/cart',
)()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TableSetupLazyRoute = TableSetupLazyRouteImport.update({
  id: '/table/setup',
  path: '/table/setup',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/table/setup.lazy').then((d) => d.Route))
const AdminTablesLazyRoute = AdminTablesLazyRouteImport.update({
  id: '/admin/tables',
  path: '/admin/tables',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/admin/tables.lazy').then((d) => d.Route))
const AdminStatisticsLazyRoute = AdminStatisticsLazyRouteImport.update({
  id: '/admin/statistics',
  path: '/admin/statistics',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/admin/statistics.lazy').then((d) => d.Route),
)
const AdminMenusLazyRoute = AdminMenusLazyRouteImport.update({
  id: '/admin/menus',
  path: '/admin/menus',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/admin/menus.lazy').then((d) => d.Route))
const AdminLoginLazyRoute = AdminLoginLazyRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/admin/login.lazy').then((d) => d.Route))
const AdminDashboardLazyRoute = AdminDashboardLazyRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/admin/dashboard.lazy').then((d) => d.Route),
)
const AdminCategoriesLazyRoute = AdminCategoriesLazyRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/admin/categories.lazy').then((d) => d.Route),
)
const TableTableNoOrderLazyRoute = TableTableNoOrderLazyRouteImport.update({
  id: '/table/$tableNo/order',
  path: '/table/$tableNo/order',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/table/$tableNo/order.lazy').then((d) => d.Route),
)
const TableTableNoMenuLazyRoute = TableTableNoMenuLazyRouteImport.update({
  id: '/table/$tableNo/menu',
  path: '/table/$tableNo/menu',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/table/$tableNo/menu.lazy').then((d) => d.Route),
)
const TableTableNoHistoryLazyRoute = TableTableNoHistoryLazyRouteImport.update({
  id: '/table/$tableNo/history',
  path: '/table/$tableNo/history',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/table/$tableNo/history.lazy').then((d) => d.Route),
)
const TableTableNoCartLazyRoute = TableTableNoCartLazyRouteImport.update({
  id: '/table/$tableNo/cart',
  path: '/table/$tableNo/cart',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/table/$tableNo/cart.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/categories': typeof AdminCategoriesLazyRoute
  '/admin/dashboard': typeof AdminDashboardLazyRoute
  '/admin/login': typeof AdminLoginLazyRoute
  '/admin/menus': typeof AdminMenusLazyRoute
  '/admin/statistics': typeof AdminStatisticsLazyRoute
  '/admin/tables': typeof AdminTablesLazyRoute
  '/table/setup': typeof TableSetupLazyRoute
  '/table/$tableNo/cart': typeof TableTableNoCartLazyRoute
  '/table/$tableNo/history': typeof TableTableNoHistoryLazyRoute
  '/table/$tableNo/menu': typeof TableTableNoMenuLazyRoute
  '/table/$tableNo/order': typeof TableTableNoOrderLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/categories': typeof AdminCategoriesLazyRoute
  '/admin/dashboard': typeof AdminDashboardLazyRoute
  '/admin/login': typeof AdminLoginLazyRoute
  '/admin/menus': typeof AdminMenusLazyRoute
  '/admin/statistics': typeof AdminStatisticsLazyRoute
  '/admin/tables': typeof AdminTablesLazyRoute
  '/table/setup': typeof TableSetupLazyRoute
  '/table/$tableNo/cart': typeof TableTableNoCartLazyRoute
  '/table/$tableNo/history': typeof TableTableNoHistoryLazyRoute
  '/table/$tableNo/menu': typeof TableTableNoMenuLazyRoute
  '/table/$tableNo/order': typeof TableTableNoOrderLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/categories': typeof AdminCategoriesLazyRoute
  '/admin/dashboard': typeof AdminDashboardLazyRoute
  '/admin/login': typeof AdminLoginLazyRoute
  '/admin/menus': typeof AdminMenusLazyRoute
  '/admin/statistics': typeof AdminStatisticsLazyRoute
  '/admin/tables': typeof AdminTablesLazyRoute
  '/table/setup': typeof TableSetupLazyRoute
  '/table/$tableNo/cart': typeof TableTableNoCartLazyRoute
  '/table/$tableNo/history': typeof TableTableNoHistoryLazyRoute
  '/table/$tableNo/menu': typeof TableTableNoMenuLazyRoute
  '/table/$tableNo/order': typeof TableTableNoOrderLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/menus'
    | '/admin/statistics'
    | '/admin/tables'
    | '/table/setup'
    | '/table/$tableNo/cart'
    | '/table/$tableNo/history'
    | '/table/$tableNo/menu'
    | '/table/$tableNo/order'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/menus'
    | '/admin/statistics'
    | '/admin/tables'
    | '/table/setup'
    | '/table/$tableNo/cart'
    | '/table/$tableNo/history'
    | '/table/$tableNo/menu'
    | '/table/$tableNo/order'
  id:
    | '__root__'
    | '/'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/menus'
    | '/admin/statistics'
    | '/admin/tables'
    | '/table/setup'
    | '/table/$tableNo/cart'
    | '/table/$tableNo/history'
    | '/table/$tableNo/menu'
    | '/table/$tableNo/order'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminCategoriesLazyRoute: typeof AdminCategoriesLazyRoute
  AdminDashboardLazyRoute: typeof AdminDashboardLazyRoute
  AdminLoginLazyRoute: typeof AdminLoginLazyRoute
  AdminMenusLazyRoute: typeof AdminMenusLazyRoute
  AdminStatisticsLazyRoute: typeof AdminStatisticsLazyRoute
  AdminTablesLazyRoute: typeof AdminTablesLazyRoute
  TableSetupLazyRoute: typeof TableSetupLazyRoute
  TableTableNoCartLazyRoute: typeof TableTableNoCartLazyRoute
  TableTableNoHistoryLazyRoute: typeof TableTableNoHistoryLazyRoute
  TableTableNoMenuLazyRoute: typeof TableTableNoMenuLazyRoute
  TableTableNoOrderLazyRoute: typeof TableTableNoOrderLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table/setup': {
      id: '/table/setup'
      path: '/table/setup'
      fullPath: '/table/setup'
      preLoaderRoute: typeof TableSetupLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tables': {
      id: '/admin/tables'
      path: '/admin/tables'
      fullPath: '/admin/tables'
      preLoaderRoute: typeof AdminTablesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/statistics': {
      id: '/admin/statistics'
      path: '/admin/statistics'
      fullPath: '/admin/statistics'
      preLoaderRoute: typeof AdminStatisticsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/menus': {
      id: '/admin/menus'
      path: '/admin/menus'
      fullPath: '/admin/menus'
      preLoaderRoute: typeof AdminMenusLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table/$tableNo/order': {
      id: '/table/$tableNo/order'
      path: '/table/$tableNo/order'
      fullPath: '/table/$tableNo/order'
      preLoaderRoute: typeof TableTableNoOrderLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table/$tableNo/menu': {
      id: '/table/$tableNo/menu'
      path: '/table/$tableNo/menu'
      fullPath: '/table/$tableNo/menu'
      preLoaderRoute: typeof TableTableNoMenuLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table/$tableNo/history': {
      id: '/table/$tableNo/history'
      path: '/table/$tableNo/history'
      fullPath: '/table/$tableNo/history'
      preLoaderRoute: typeof TableTableNoHistoryLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table/$tableNo/cart': {
      id: '/table/$tableNo/cart'
      path: '/table/$tableNo/cart'
      fullPath: '/table/$tableNo/cart'
      preLoaderRoute: typeof TableTableNoCartLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminCategoriesLazyRoute: AdminCategoriesLazyRoute,
  AdminDashboardLazyRoute: AdminDashboardLazyRoute,
  AdminLoginLazyRoute: AdminLoginLazyRoute,
  AdminMenusLazyRoute: AdminMenusLazyRoute,
  AdminStatisticsLazyRoute: AdminStatisticsLazyRoute,
  AdminTablesLazyRoute: AdminTablesLazyRoute,
  TableSetupLazyRoute: TableSetupLazyRoute,
  TableTableNoCartLazyRoute: TableTableNoCartLazyRoute,
  TableTableNoHistoryLazyRoute: TableTableNoHistoryLazyRoute,
  TableTableNoMenuLazyRoute: TableTableNoMenuLazyRoute,
  TableTableNoOrderLazyRoute: TableTableNoOrderLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
